steps:
  - label: ":java: :elasticsearch: Elasticsearch Java API client DRA - {{matrix.workflow}}"
    agents:
      provider: "gcp"
    branches: [ "main", "8.10", "7.17" ]
    matrix:
      setup:
        workflow:
          - "snapshot"
          - "staging"
    command: ".ci/release_dra.sh {{matrix.workflow}}"
